# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/chess/OneDrive/Documents/Stanford/EE272C/digilent-xdc-master/digilent-xdc-master/Zedboard-Master.xdc

# Block Designs: bd/cgra_test_design/cgra_test_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cgra_test_design || ORIG_REF_NAME==cgra_test_design} -quiet] -quiet

# IP: bd/cgra_test_design/ip/cgra_test_design_processing_system7_0_0/cgra_test_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cgra_test_design_processing_system7_0_0 || ORIG_REF_NAME==cgra_test_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/cgra_test_design/ip/cgra_test_design_axi_gpio_0_0/cgra_test_design_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cgra_test_design_axi_gpio_0_0 || ORIG_REF_NAME==cgra_test_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/cgra_test_design/ip/cgra_test_design_axi_gpio_0_1/cgra_test_design_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cgra_test_design_axi_gpio_0_1 || ORIG_REF_NAME==cgra_test_design_axi_gpio_0_1} -quiet] -quiet

# IP: bd/cgra_test_design/ip/cgra_test_design_clk_wiz_0_0/cgra_test_design_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cgra_test_design_clk_wiz_0_0 || ORIG_REF_NAME==cgra_test_design_clk_wiz_0_0} -quiet] -quiet

# IP: bd/cgra_test_design/ip/cgra_test_design_xbar_0/cgra_test_design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cgra_test_design_xbar_0 || ORIG_REF_NAME==cgra_test_design_xbar_0} -quiet] -quiet

# IP: bd/cgra_test_design/ip/cgra_test_design_ps7_0_axi_periph_0/cgra_test_design_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cgra_test_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==cgra_test_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/cgra_test_design/ip/cgra_test_design_rst_ps7_0_100M_0/cgra_test_design_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cgra_test_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==cgra_test_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/cgra_test_design/ip/cgra_test_design_cgra_loader_0_0/cgra_test_design_cgra_loader_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cgra_test_design_cgra_loader_0_0 || ORIG_REF_NAME==cgra_test_design_cgra_loader_0_0} -quiet] -quiet

# IP: bd/cgra_test_design/ip/cgra_test_design_auto_pc_0/cgra_test_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cgra_test_design_auto_pc_0 || ORIG_REF_NAME==cgra_test_design_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/chess/OneDrive/Documents/Stanford/EE272C/CGRA_IO_TEST/CGRA_IO_TEST.gen/sources_1/bd/cgra_test_design/cgra_test_design_ooc.xdc
